
# NOTICE: Strongly recommended to subsequently add autogenerated annotation to improve Retrieval-Augmented-Generation (RAG) with _semanticAssist .

_knowledge-arduinoUbiquitous() {
    [[ "$objectName" != "arduinoUbiquitous" ]] && _stop 1

    _safeRMR "$scriptLocal"/knowledge/arduinoUbiquitous
    mkdir -p "$scriptLocal"/knowledge/arduinoUbiquitous

    mkdir -p "$scriptLocal"/knowledge/arduinoUbiquitous/_local
    cp "$scriptAbsoluteFolder"/_local/ops.sh "$scriptLocal"/knowledge/arduinoUbiquitous/_local/

    mkdir -p "$scriptLocal"/knowledge/arduinoUbiquitous/_lib
    cp -r "$scriptAbsoluteFolder"/_lib/_examples "$scriptLocal"/knowledge/arduinoUbiquitous/_lib/
    cp -r "$scriptAbsoluteFolder"/_lib/udev_teensy-rules "$scriptLocal"/knowledge/arduinoUbiquitous/_lib/

    mkdir -p "$scriptLocal"/knowledge/arduinoUbiquitous/_lib/openocd-static
    cp -r "$scriptAbsoluteFolder"/_lib/openocd-static/_prog "$scriptLocal"/knowledge/arduinoUbiquitous/_lib/openocd-static/
    mkdir -p "$scriptLocal"/knowledge/arduinoUbiquitous/_lib/openocd-static/_lib/app/udev
    cp -r "$scriptAbsoluteFolder"/_lib/openocd-static/_lib/app/udev/rules "$scriptLocal"/knowledge/arduinoUbiquitous/_lib/openocd-static/_lib/app/udev/

    #cp -r "$scriptAbsoluteFolder"/_lib/_build-staging-ops.sh "$scriptLocal"/knowledge/arduinoUbiquitous/_lib/

    cp -r "$scriptAbsoluteFolder"/_prog "$scriptLocal"/knowledge/arduinoUbiquitous/
    #cp -r "$scriptAbsoluteFolder"/_prog-ops "$scriptLocal"/knowledge/arduinoUbiquitous/

    #cp -r "$scriptAbsoluteFolder"/.devops "$scriptLocal"/knowledge/arduinoUbiquitous/
    cp -r "$scriptAbsoluteFolder"/.github "$scriptLocal"/knowledge/arduinoUbiquitous/

    #cp -r "$scriptAbsoluteFolder"/ops "$scriptLocal"/knowledge/arduinoUbiquitous/
    
    cp -r "$scriptAbsoluteFolder"/fork "$scriptLocal"/knowledge/arduinoUbiquitous/
    cp -r "$scriptAbsoluteFolder"/upgrade "$scriptLocal"/knowledge/arduinoUbiquitous/

    #cp -r "$scriptAbsoluteFolder"/license-llama "$scriptLocal"/knowledge/arduinoUbiquitous/
    #cp "$scriptAbsoluteFolder"/Notice.txt "$scriptLocal"/knowledge/arduinoUbiquitous/
    cp "$scriptAbsoluteFolder"/license.txt "$scriptLocal"/knowledge/arduinoUbiquitous/
    #cp "$scriptAbsoluteFolder"/license-installer.txt "$scriptLocal"/knowledge/arduinoUbiquitous/
    cp "$scriptAbsoluteFolder"/agpl-3.0.txt "$scriptLocal"/knowledge/arduinoUbiquitous/
    cp "$scriptAbsoluteFolder"/gpl-3.0.txt "$scriptLocal"/knowledge/arduinoUbiquitous/

    #cp "$scriptAbsoluteFolder"/README.sh.out.txt "$scriptLocal"/knowledge/arduinoUbiquitous/
    #cp "$scriptAbsoluteFolder"/README-installer.pdf "$scriptLocal"/knowledge/arduinoUbiquitous/
    #cp "$scriptAbsoluteFolder"/README-live.pdf "$scriptLocal"/knowledge/arduinoUbiquitous/
    cp "$scriptAbsoluteFolder"/README.md "$scriptLocal"/knowledge/arduinoUbiquitous/
}
